Add in dynamic image creation for ARM64 (Apple Sillicon)
uci-uav-forge/uavf_2024 pull request #36
Opened 2023-10-19 06:07 UTC by Dat-Bois

Title pretty much says it all.

When the repo is now cloned and a fresh image is needed, just run "python3 setup_image.py" and it will generate the .devcontainer/dockerfile for your respective architecture based on the template in the main. 

For X11 forwarding in the devcontainer.json it is by default set for x86 and will not pose any build issues for arm64. To use X11 forwarding on mac just change the line. Once merged I can update the readme accordingly to explain the X11 (with one extra step for macs).

2023-10-19 16:35 UTC, EricPedley requested changes
![image](https://github.com/uci-uav-forge/uavf_2024/assets/48658337/b1db6a4f-1971-4467-a47e-cb7f1853c962)
Doesn't work on my machine 😢  
Also, merge conflicts. Do you need help resolving them?

2023-10-21 18:44 UTC, Dat-Bois commented
I can resolve the merge conflicts, some stuff will need to overwrite what's in the current repo (ie the things in .devcontainer). Also the error is weird, because there shouldn't be any ADD command in the dockerfile anymore. Try pulling again?

2023-10-22 08:11 UTC, EricPedley commented
Ok you're right, it does work, I think I just msised the `python3 setup_image.py` step. LMK if you have any problems with the merge conflicts. Once you're done fixing them, re-request my review so I can approve this.

2023-10-23 06:27 UTC, Vince-C156 approved these changes

2023-10-23 16:42 UTC, EricPedley approved these changes

2023-10-23 16:42 UTC, merged